parameters:

services:

    fixtures.source:
        class: Ryzhov\Bundle\FixturesBundle\Service\FixturesSource
        arguments: ["@kernel","@fixtures.csv_transformer"]

    fixtures.csv_transformer:
        class: Ryzhov\Bundle\FixturesBundle\Service\CsvTransformer

    Ryzhov\Bundle\FixturesBundle\Service\FixturesSource: '@fixtures.source'
    Ryzhov\Bundle\FixturesBundle\Service\CsvTransformer: '@fixtures.csv_transformer'
